name: Unit tests
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - name: Setup Python
        uses: actions/setup-python@v6.2.0
        with:
          python-version: 3.13
      - name: Install tox
        run: pip install tox
      - name: Install local pkg
        run: pip install .
      - name: Linters
        run: tox -e lint
      - name: Tests
        run: tox
